### ISSUE TITLE
"attempt to subtract with overflow"

### ISSUE THREAD

**Issue by zaibacu** [EasyPost/rust-mysql-binlog#13]
I have one concrete binlog file which causes this error while trying to parse events.

It refers to this line: https://github.com/EasyPost/rust-mysql-binlog/blob/master/src/event.rs#L488 

I can upload concrete binlog file, but is 100Mb :)

**Comment by Roguelazer** [comment]
What version of mysql was the binlog file generated with?

Based on my reading of the spec, it's either from a bizarre version of MySQL, or it's corrupted; the header should always be 19 bytes.

**Comment by zaibacu** [comment]
That's MariaDB 10.6.4

It may be corrupted, because there are 14 binlog files in total and only one is causing such problems

**Comment by Roguelazer** [comment]
If it's not confidential and you're willing to share it with me, you can drop it in my personal dropbox account at https://www.dropbox.com/request/Pc7ZcXDdd98QpUkW5b22 and I'll see if I can make the library tolerant of whatever kind of corruption this is

**Comment by zaibacu** [comment]
I've found out, that this is a problem from my side. I misunderstood offset parameter. Used same offset and crawled through all binlogs till I found some new records. It turns out, I need to reset offset to 0 each time new file is being parsed
