### ISSUE TITLE
MyString support

### ISSUE THREAD

**Issue by zaibacu** [EasyPost/rust-mysql-binlog#14]
Got following exception while reading binlog of MariaDB (mysql  Ver 15.1 Distrib 10.3.21-MariaDB, for Linux (x86_64) using readline 5.1 )

> thread 'main' panicked at 'not implemented: unimplemented stringy type MyString
> mysql_binlog-0.3.2/src/column_types.rs:120:26

**Comment by Roguelazer** [comment]
This should be fixed as of v0.4.0, just released

Note that we don't properly handle encodings, so a MyString that corresponds to a `BINARY` / `VARBINARY` column (or, really, anything other than UTF-8 string) will probably not work correctly.
