### ISSUE TITLE
Serialize defined multiple of times

### ISSUE THREAD

**Issue by zaibacu** [EasyPost/rust-mysql-binlog#9]
I'm getting following error when trying to use it.
```
  |
5 | use serde::{Serialize, Serializer};
  |             --------- previous import of the macro `Serialize` here
6 | use serde_derive::Serialize;
  |     ^^^^^^^^^^^^^^^^^^^^^^^ `Serialize` reimported here
  |
  = note: `Serialize` must be defined only once in the macro namespace of this module
```

Seems to be telling the truth: https://github.com/EasyPost/rust-mysql-binlog/blob/master/src/value.rs#L4

**Comment by Roguelazer** [comment]
Ah, this is a change in newer versions of Serde. I'll fix it.

**Comment by Roguelazer** [comment]
(specifically, `derive` behavior can be exposed from `serde` directly via a feature, and I imagine one of your other dependencies is selecting that feature)

**Comment by Roguelazer** [comment]
v0.3.2 is now available on crates.io which fixes this issue

thanks for reporting!

**Comment by zaibacu** [comment]
Thank you for fixing :)
